title = "gitleaks custom config"

[[rules]]
	description = "Detect private keys"
	regex = '''-----BEGIN (:?[A-Z\-\s]*)PRIVATE KEY-----'''
	tags = ["private-keys"]
	
[[rules]]
	description = "Detect passwords/secrets/apikey"
	regex = '''(?i)(password|pass|pwd|passwd|secret|apikey|api_key|api\-key)\s*(=|:)\s*.+'''
	tags = ["passwords", "secrets", "apikey"]
	
[[rules]]
	description = "Detect UUID/GUID"
	regex = '''[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'''
	tags = ["uuid", "guid"]
	
[[rules]]
	description = "Detect SHA224/SHA256/SHA384/SHA512 hashes"
	regex = '''[0-9A-Fa-f]{56,128}'''
	tags = ["sha224", "sha256", "sha384", "sha512"]	
	
[[rules]]
	description = "Detect password hashes"
	regex = '''\$[a-zA-Z0-9]+\$[a-zA-Z0-9/\.\$=]{5,}'''
	tags = ["password-hash"]
	
[[rules]]
	description = "Detect private IPv4 range 10"
	regex = '''10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''
	tags = ["private-ipv4"]
	
[[rules]]
	description = "Detect private IPv4 range 172.16"
	regex = '''172\.16\.[0-9]{1,3}\.[0-9]{1,3}'''
	tags = ["private-ipv4"]		

[[rules]]
	description = "Detect private IPv4 range 192.168"
	regex = '''192\.168\.[0-9]{1,3}\.[0-9]{1,3}'''
	tags = ["private-ipv4"]
